/cloud_registered:
  history: keep_last
  depth: 20
  reliability: best_effort
  durability: volatile
/cloud_registered_full:
  history: keep_last
  depth: 20
  reliability: best_effort
  durability: volatile
/Odometry:
  history: keep_last
  depth: 50
  reliability: best_effort
  durability: volatile
