pgm2esdf_generator:
  ros__parameters:
    map_yaml: "/home/ros2_ws/src/mas2027_nav_bringup/map/lab3.yaml"
    output_pcd: "/home/ros2_ws/src/mas2027_nav_bringup/pcd/lab3_esdf.pcd"
    max_dist: 5.0
    occupied_thresh: 0.65
    free_thresh: 0.25
    treat_unknown_as_obstacle: false
    unknown_gray_values: [205]
